BOT_TOKEN:
MAIN_SERVER_ID:
STAFF_SERVER_ID:
MAIN_APPLICATION_CATEGORY_ID:
STAFF_APPLICATION_CHANNEL_ID:
STAFF_APPLICATION_ROLE_ID:
EX_MEMBER_ROLE:
STARFISH_ROLES: []
MANATEE_ROLES: []
PIRANHA_ROLES: []
BARRACUDA_ROLES: []
ANGLER_ROLES: []
HAMMERHEAD_ROLES: []
SAILFISH_ROLES: []
DOLPHIN_ROLES: []
NARWHAL_ROLES: []
COMMON_ROLES: []
MAIN_GUILD_GENERAL_CHANNEL_ID:
GUILD_LOG_CHANNEL_ID:
GUILD_FAQ_CHANNEL_ID:
GUILD_ROLE_CHANEL_ID:
GUILD_WAR_FAQ_CHANNEL_ID: